name: drugexr-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - rdkit
  - tqdm
  - pytorch
  - matplotlib
  - seaborn
  - scikit-learn
  - numpy
  - pandas
  - click
  # DEV ONLY
  - jupyter
  - black
  - pytest
  - pip:
    - pyprojroot
    # DEV ONLY
    - Sphinx
    - isort