name: drugexr-dev
channels:
  - conda-forge
  - defaults
  - mamba
dependencies:
  - python=3.7
  - pip
  - rdkit
  - tqdm
  - pytorch
  - cudatoolkit=11.3
  - matplotlib
  - seaborn
  - scikit-learn
  - numpy
  - pandas
  - click
  # DEV ONLY
  - dvc
  - jupyter
  - black
  - pytest
  - pip:
    - git+https://github.com/reymond-group/RAscore.git@master
    - pyprojroot
    # DEV ONLY
    - Sphinx
    - isort