name: drugexr
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.7
  - pip
  - rdkit
  - tqdm
  - pytorch-lightning=1.5.3
  - matplotlib
  - scikit-learn=0.22.1
  - numpy
  - pandas
  - click
  # DEV ONLY
  - jupyter
  - black
  - pytest
  - pip:
    - git+https://github.com/reymond-group/RAscore.git@master
    - pyprojroot
    # DEV ONLY
    - Sphinx
    - isort
    - mlflow
    - python-dotenv
