name: drugexr-dev
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.7
  - pip
  - rdkit
  - tqdm
  - pytorch::pytorch
  - nvidia::cudatoolkit=11.3
  - pytorch-lightning=1.5.3
  - matplotlib
  - seaborn
  - scikit-learn
  - numpy
  - pandas
  - click
  # DEV ONLY
  - jupyter
  - black
  - pytest
  - pip:
    - git+https://github.com/reymond-group/RAscore.git@master
    - pyprojroot
    # DEV ONLY
    - Sphinx
    - isort
    - mlflow
    - python-dotenv